#! /bin/sh

case "$1" in
    start)
        echo "Starting aesdsocket"
        aesdsocket -d
        ;;
    stop)
        echo "Stopping aesdsocket"
        killall -TERM aesdsocket
        ;;
 
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
    esac

exit 0